---
  header_logo_url: https://sfg.taxonworks.org/s/78q89i
  header_logo_text: Plecoptera Species File
  header_links:
    - label: Home
      link: /

    - label: Search DwC
      link: /resources/tw/filter/dwc_otus

    - label: About
      link: /about

    - label: Perla
      link: /perla
