taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:type
          - panel:type-specimen
          - panel:nomenclature
          - panel:nomenclature-references

        - - panel:map
          - panel:descendants
          - panel:content
          - panel:keys
          - panel:statistics
          - panel:etymology
          - panel:gbif
          - panel:sounds
  inaturalist:
      label: 'iNaturalist'
      rank_group: ['GenusGroup', 'SpeciesGroup']
      panels:
        - - - panel:inaturalist
